monolog:
  channels:
    - deprecation
  handlers:
    main:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: info
      channels: ["!deprecation"]
    deprecation:
      type: rotating_file
      path: "%kernel.logs_dir%/deprecations/%kernel.environment%.log"
      max_files: 2
      level: debug
      channels: [deprecation]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console", "!deprecation"]